<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WIN-01607201740" name="com.sugon.timeout.TestTimeout" tests="2" failures="0" timestamp="15 三月 2018 07:59:14 GMT" time="5.380" errors="1">
  <testcase name="testThisShouldPass" time="4.002" classname="com.sugon.timeout.TestTimeout"/>
  <testcase name="testThisShouldFail" time="1.378" classname="com.sugon.timeout.TestTimeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.sugon.timeout.TestTimeout.testThisShouldFail() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.sugon.timeout.TestTimeout.testThisShouldFail() didn't finish within the time-out 1000
at com.sugon.timeout.TestTimeout.testThisShouldFail(TestTimeout.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testThisShouldFail -->
</testsuite> <!-- com.sugon.timeout.TestTimeout -->
